In [1]:
import pandas as pd

In [2]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [3]:
df = pd.read_csv("Spam_Email.csv")
df.head(5)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [4]:
df.groupby('spam').describe()

text                                                               
     count unique                                                top freq
spam                                                                     
0     4360   4327  Subject: * special notification * aurora versi...    2
1     1368   1368  Subject: naturally irresistible your corporate...    1

In [5]:
x_train , x_test , y_train , y_test = train_test_split(df['text'],df['spam'],test_size=0.20)

In [6]:
corpus = [
    'This is first document',#1
    'This document is the second document',#2
    'And this is the third one',#3
    'Is this the first document',#4
]
vectorizer = CountVectorizer()

In [7]:
x = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())

['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']


Unique words in each 4 document.
We have 9 unique words
these 9 words are the features and will consided as columns

In [8]:
print(x.toarray())

[[0 1 1 1 0 0 0 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [9]:
x_train

5451    Subject: 2001 group expenses  guys , attached ...
4041    Subject: 3 - urgent - to prevent loss of infor...
2437    Subject: re : spring workshop  folks :  it is ...
3554    Subject: risk 2000 - boston  dear vince ,  i a...
2027    Subject: re : seismic data on oil & gas field ...
                              ...                        
2125    Subject: re : vincent tang  vince - thanks so ...
5097    Subject: re : argentina power & gas market mod...
3099    Subject: market maker simulation v . 2  stinso...
5665    Subject: uk inflation presentation  deal all ,...
4026    Subject: west power model  lance and i spoke w...
Name: text, Length: 4582, dtype: object

In [10]:
vector = CountVectorizer()
x_train_count = vector.fit_transform(x_train.values)
x_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [11]:
y_train

5451    0
4041    0
2437    0
3554    0
2027    0
       ..
2125    0
5097    0
3099    0
5665    0
4026    0
Name: spam, Length: 4582, dtype: int64

In [12]:
model = MultinomialNB()
model.fit(x_train_count,y_train)

MultinomialNB()

please call our service representive on 8080 between
10AM-9AM as you have won a guarenteed $1000 cash prize!

In [15]:
emails = [
    "please call our service representive on 8080 between 10AM-9AM as you have won a guarenteed $1000 cash prize!"
]
emails_count = vector.transform(emails)
test = model.predict(emails_count)
for i in test:
    if i == 0:
        print("Ham Email")
    elif i==1:
        print("Spam Email")



Spam Email


In [14]:
x_test_count = vector.transform(x_test)
model.score(x_test_count,y_test)

0.9912739965095986