In [1]:
import numpy as np


In [2]:
my_list = [1, 2, 3, 4, 5]
my_list

[1, 2, 3, 4, 5]

In [3]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [4]:
my_matrix = [[1, 2, 3], 
             [4, 5, 6], 
             [7, 8, 9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#return evenly spaced values within a given interval

In [5]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [7]:
#Zeros and one
#Generate array of zeros and ones

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#Linspace
Return evenly spaced numbers over a specified interval.

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [16]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

# Create a Identity Matrix

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.random.rand(2)

array([0.64174484, 0.61125285])

In [19]:
np.random.rand(5,5)

array([[0.24826436, 0.8924398 , 0.85841137, 0.13689237, 0.46465938],
       [0.22679144, 0.12332124, 0.86087376, 0.13753896, 0.7928844 ],
       [0.89754698, 0.41917222, 0.01350702, 0.12659934, 0.9245188 ],
       [0.72789453, 0.00230308, 0.9887091 , 0.2534082 , 0.44425105],
       [0.05101551, 0.13147182, 0.05551312, 0.85465078, 0.2410008 ]])

In [20]:
np.random.randint(1,100)

8

In [21]:
np.random.randint(1,100,10)

array([83, 32, 56, 56, 99, 22, 27, 60, 49, 35])